//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioPredictivo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargaTemporal
    {
        public int PK { get; set; }
        public Nullable<int> CODIGO { get; set; }
        public Nullable<int> DIA1 { get; set; }
        public Nullable<int> DIA2 { get; set; }
        public Nullable<int> DIA3 { get; set; }
        public Nullable<int> DIA4 { get; set; }
        public Nullable<int> DIA5 { get; set; }
        public Nullable<int> DIA6 { get; set; }
        public Nullable<int> DIA7 { get; set; }
        public Nullable<int> DIA8 { get; set; }
        public Nullable<int> DIA9 { get; set; }
        public Nullable<int> DIA10 { get; set; }
        public Nullable<int> DIA11 { get; set; }
    }
}
