//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebReposicion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleReposicion
    {
        public int IdDetalle { get; set; }
        public Nullable<int> NroReposicion { get; set; }
        public Nullable<int> PkArticulo { get; set; }
        public Nullable<int> Almacen { get; set; }
        public string CodigoArticulo { get; set; }
        public string NombreArticulo { get; set; }
        public string Categoria { get; set; }
        public Nullable<int> Cantidad { get; set; }
    }
}
