//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtraerPrediccion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBPREDICTIVOEntities : DbContext
    {
        public DBPREDICTIVOEntities()
            : base("name=DBPREDICTIVOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CargaTemporal> CargaTemporal { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
    
        public virtual int sp_cargarStockPredictivo(Nullable<int> stockPredictivo, Nullable<int> codigoArticulo)
        {
            var stockPredictivoParameter = stockPredictivo.HasValue ?
                new ObjectParameter("StockPredictivo", stockPredictivo) :
                new ObjectParameter("StockPredictivo", typeof(int));
    
            var codigoArticuloParameter = codigoArticulo.HasValue ?
                new ObjectParameter("CodigoArticulo", codigoArticulo) :
                new ObjectParameter("CodigoArticulo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_cargarStockPredictivo", stockPredictivoParameter, codigoArticuloParameter);
        }
    }
}
