//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtraerPrediccion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int CodigoArticulo { get; set; }
        public Nullable<int> StockFisico { get; set; }
        public Nullable<int> StockComprometido { get; set; }
        public Nullable<int> StockDisponible { get; set; }
        public string ClasificacionABC { get; set; }
        public string ClasificacionXYZ { get; set; }
        public Nullable<int> StockPredictivo { get; set; }
        public Nullable<int> StockMinimo { get; set; }
        public Nullable<int> StockMaximo { get; set; }
        public string PrioridadReposicion { get; set; }
    }
}
